bin/Cargo.toml, docs/02 Getting Started/2.1 Installation.md
Also closes #14 
could this be `hacktoberfest-accepted` as well?
=> `ogma-bin` -> `ogma`

ogma/src/common/err.rs, ogma/src/eng/annotate.rs, ogma/src/eng/arg.rs, ogma/src/eng/blk.rs, ogma/src/eng/comp/infer.rs, ogma/src/eng/comp/mod.rs, ogma/src/eng/comp/params.rs, ogma/src/eng/graphs/mod.rs, ogma/src/eng/mod.rs, ogma/src/lang/defs.rs, ogma/src/lang/impls/intrinsics/cmp.rs, ogma/src/lang/impls/intrinsics/mod.rs, ogma/src/lang/syntax/ast.rs, ogma/src/lang/syntax/parse.rs, ogma/src/lang/types.rs, ogma/src/rt/bat.rs
Works on reducing the size of structures passed around to reduce memory pressure.
=> Reduce structure sizing

ogma/src/common/err.rs, ogma/src/eng/comp/infer.rs, ogma/src/eng/comp/mod.rs, ogma/src/eng/comp/params.rs, ogma/src/eng/comp/resolve_tg.rs, ogma/src/eng/graphs/astgraph.rs, ogma/src/eng/graphs/mod.rs, ogma/src/eng/graphs/tygraph.rs, ogma/src/lang/syntax/ast.rs, ogma/src/lang/syntax/parse.rs, ogma/tests/commands/annotation.rs, ogma/tests/commands/mod.rs
=> Type annotation

docs/01 Introduction.md, docs/02 Getting Started/2.2 FizzBuzz.md, docs/05 Syntax and Semantics/5.3 Typing.md
=> Docs add ty inference

Cargo.lock, RELEASE.md, docs/05 Syntax and Semantics/5.1 Syntax.md, ogma/src/common/err.rs, ogma/src/eng/annotate.rs, ogma/src/eng/arg.rs, ogma/src/eng/graphs/astgraph.rs, ogma/src/eng/graphs/tygraph.rs, ogma/tests/commands/mod.rs, ogma/tests/commands/types.rs
=> Newline literal

RELEASE.md, ogma/src/lang/impls/intrinsics/morphism.rs, ogma/tests/commands/morphism.rs
=> Filter on str

RELEASE.md, ogma/src/lang/impls/intrinsics/io.rs
=> map file into BufWriter

RELEASE.md, ogma/src/common/err.rs, ogma/src/eng/comp/mod.rs, ogma/src/eng/graphs/astgraph.rs, ogma/src/lang/defs.rs, ogma/src/lang/impls/intrinsics/pipeline.rs, ogma/src/lang/impls/mod.rs, ogma/tests/commands/definitions.rs, ogma/tests/commands/mod.rs, ogma/tests/commands/pipeline.rs
=> Better not defined error

RELEASE.md, ogma/src/lang/impls/intrinsics/pipeline.rs, ogma/tests/commands/annotation.rs, ogma/tests/commands/morphism.rs, ogma/tests/commands/pipeline.rs
=> Dot op infer output

RELEASE.md, ogma/src/common/err.rs, ogma/src/eng/comp/mod.rs, ogma/src/eng/graphs/locals_graph.rs, ogma/tests/commands/mod.rs, ogma/tests/commands/pipeline.rs
=> Extend variable sealing to OpNode's arguments when sealing

Cargo.lock, ogma/src/eng/comp/mod.rs, ogma/src/eng/comp/params.rs, ogma/src/eng/comp/resolve_tg.rs, ogma/src/lang/impls/intrinsics/pipeline.rs, ogma/tests/commands/mod.rs
Alter the failure mode for locals resolving to allow for compilation.
Fixes #80 #106
=> Fix variable type inferencing for defs

Cargo.lock, ogma/src/eng/blk.rs, ogma/src/eng/comp/infer.rs, ogma/src/eng/comp/mod.rs, ogma/src/eng/comp/params.rs, ogma/src/eng/comp/resolve_tg.rs, ogma/src/eng/graphs/astgraph.rs, ogma/src/eng/mod.rs, ogma/src/lang/impls/intrinsics/pipeline.rs, ogma/tests/commands/errs.rs, ogma/tests/commands/mod.rs
=> Detect trailing cmd and suggest a pipe (in `let` cmd)

ogma/src/eng/comp/resolve_tg.rs, ogma/src/eng/graphs/tygraph.rs, ogma/tests/commands/mod.rs, ogma/tests/doc-examples.rs
=> Extend the backpropagation if the to.input is Known

RELEASE.md, ogma/src/eng/blk.rs, ogma/src/eng/graphs/mod.rs, ogma/src/lang/defs.rs, ogma/src/lang/impls/intrinsics/arithmetic.rs, ogma/src/lang/impls/intrinsics/cmp.rs, ogma/src/lang/impls/intrinsics/io.rs, ogma/src/lang/impls/intrinsics/logic.rs, ogma/src/lang/impls/intrinsics/morphism.rs, ogma/src/lang/impls/intrinsics/pipeline.rs, ogma/src/lang/impls/mod.rs, ogma/src/lang/types.rs, ogma/tests/commands/arithmetic.rs, ogma/tests/commands/cmp.rs, ogma/tests/commands/definitions.rs, ogma/tests/commands/io.rs, ogma/tests/commands/mod.rs, ogma/tests/commands/morphism.rs, ogma/tests/commands/pipeline.rs, ogma/tests/doc-examples.rs
Collection of changes which closes #120 
Closes #125 
Closes #126 
Closes #127 
Closes #128
Closes #129 
Closes #130
Closes #131
Closes #132
=> Split intrinsics

RELEASE.md, ogma/src/eng/arg.rs, ogma/src/eng/comp/resolve_tg.rs, ogma/src/eng/graphs/tygraph.rs
=> Introduce types set

RELEASE.md, ogma/src/common/err.rs, ogma/src/eng/arg.rs, ogma/src/eng/blk.rs, ogma/src/eng/comp/infer.rs, ogma/src/eng/comp/mod.rs, ogma/src/eng/comp/resolve_tg.rs, ogma/src/eng/eval.rs, ogma/src/eng/graphs/astgraph.rs, ogma/src/eng/graphs/locals_graph.rs, ogma/src/eng/graphs/mod.rs, ogma/src/eng/graphs/tygraph.rs, ogma/src/eng/mod.rs, ogma/src/lang/impls/intrinsics/cmp.rs, ogma/src/lang/impls/intrinsics/mod.rs, ogma/src/lang/impls/intrinsics/pipeline.rs, ogma/tests/commands/annotation.rs, ogma/tests/commands/definitions.rs, ogma/tests/commands/mod.rs, ogma/tests/doc-examples.rs
Closes #119 
Closes #122 
Closes #123
=> Fully move to `TypesSet`s usage in type graph

RELEASE.md, ogma/src/eng/comp/infer.rs, ogma/src/eng/graphs/astgraph.rs, ogma/src/eng/graphs/mod.rs, ogma/src/eng/graphs/tygraph.rs, ogma/tests/commands/pipeline.rs
=> Alter op target inference to check variable existence

docs/04 Common Commands.md, ogma/src/eng/comp/infer.rs, ogma/tests/commands/errs.rs, ogma/tests/doc-examples.rs
=> Better dot op type error

RELEASE.md, ogma/src/lang/syntax/parse.rs, ogma/tests/batch-files.rs, ogma/tests/commands/annotation.rs, ogma/tests/commands/errs.rs, ogma/tests/commands/types.rs
=> More verbose parsing errors

.github/workflows/publish.yml, .github/workflows/rust.yml, Cargo.toml, README.md, RELEASE.md, ogma-shell/interface/mod.rs, ogma-shell/interface/tests.rs
=> Completer spins

Cargo.lock, RELEASE.md, ogma-shell/Cargo.toml, ogma-shell/interface/mod.rs, ogma-shell/interface/outputs.rs, ogma-shell/interface/tests.rs, ogma-shell/interface/theme.rs, ogma-shell/lib.rs
Adds theming support for the shell.
Closes #150
=> Support transparent backgrounds

RELEASE.md, ogma/src/common/err.rs, ogma/src/eng/comp/mod.rs, ogma/tests/commands/mod.rs
Fixes the bug by prioritising hard errors for reporting.
=> Internal lg update bug

RELEASE.md, bin/main.rs, docs/09 Batch Files.md, ogma-shell/lib.rs, ogma/src/lang/defs.rs, ogma/src/lang/defs2/mod.rs, ogma/src/lang/defs2/partitions.rs, ogma/src/lang/mod.rs, ogma/src/lang/syntax/parse/file.rs, ogma/src/lang/syntax/parse/mod.rs, ogma/src/lang/syntax/parse/test.rs, ogma/src/rt/bat.rs, ogma/tests/batch-files.rs
Close #173 
Introduces a `defs2` module which begins adding the partitions data structure.
=> Parse a ogma file

ogma/src/lang/defs2/mod.rs, ogma/src/lang/defs2/tests.rs, ogma/src/lang/syntax/parse/file.rs
=> Introduce fs structure builder for partitions

ogma-shell/interface/outputs.rs, ogma/src/eng/arg.rs, ogma/src/eng/blk.rs, ogma/src/eng/comp/infer.rs, ogma/src/eng/comp/mod.rs, ogma/src/eng/graphs/astgraph.rs, ogma/src/eng/graphs/tygraph.rs, ogma/src/lang/defs2/partitions.rs, ogma/src/lang/impls/intrinsics/morphism.rs, ogma/src/lang/syntax/parse/file.rs, ogma/src/output/print.rs
=> Fsmap into part graph

Cargo.lock, ogma/Cargo.toml, ogma/src/lang/defs2/mod.rs, ogma/src/lang/defs2/partitions.rs, ogma/src/lang/syntax/ast.rs, ogma/src/lang/syntax/parse/file.rs
=> Resolve partition imports

Cargo.lock, ogma/Cargo.toml, ogma/src/lang/defs2/mod.rs, ogma/src/lang/defs2/partitions/item.rs, ogma/src/lang/defs2/partitions/mod.rs, ogma/src/lang/defs2/partitions/node.rs, ogma/src/lang/defs2/partitions/partset.rs, ogma/src/lang/defs2/partitions/tests.rs, ogma/src/lang/syntax/parse/file.rs, ogma/src/lib.rs
=> Replace partition graph with partition tree
